enalbe gerrit 2.2.2 upgrades, submit patch for 2.2.2, and set reviewers automatic feature
Test Plan:
* New deployment to dev39 with version specifiled (either 2.1.7 or 2.2.2)
  will get a new gerrit with the version
* Legacy deployment with 2.1.7 and upgrade options specified
  will get 2.1.7 upgrade to 2.2.2 without DB data lost
* Test Submit patch: The owner of the change will be able to submit the patch given +2
* Test if reviewers could be automatically setup per project.

Change-Id: I62d07c966ab29e43411db3be0c0494ccde165cad

diff --git a/jobs/gerrit/templates/gerrit_init.ctl.erb b/jobs/gerrit/templates/gerrit_init.ctl.erb
--- a/jobs/gerrit/templates/gerrit_init.ctl.erb
+++ b/jobs/gerrit/templates/gerrit_init.ctl.erb
@@ -5,6 +5,9 @@ JAVA_DIR=/var/vcap/packages/java
 JOB_DIR=/var/vcap/jobs/gerrit
 DATA_DIR=/var/vcap/store/gerrit
 
+VERSION=<%= properties.gerrit.version %>
+NEED_UPGRADE=<%= properties.gerrit.upgrade||0 %>
+
 <% if properties.gerrit_postgres %>
 dbname=<%= properties.gerrit_postgres.dbname||"reviewdb" %>
 <% elsif properties.gerrit_mysql %>
@@ -13,21 +16,28 @@ dbname=<%= properties.gerrit_mysql.dbname||"reviewdb" %>
 
 CONFIG_DIR=$DATA_DIR/review_site/$dbname/etc/
 
-chown vcap:vcap $PACKAGE_DIR/gerrit-2.1-SNAPSHOT.war
+chown vcap:vcap $PACKAGE_DIR/*.war
 
 if [ ! -d $CONFIG_DIR ]; then
   mkdir -p $DATA_DIR/review_site/$dbname
   chown vcap:vcap $DATA_DIR/review_site/$dbname
 
-  #use expect to general default initilization.
-  $JOB_DIR/bin/gerrit_expect
-
+  # Use expect for DB initilization.
+  $JOB_DIR/bin/gerrit_expect $VERSION
   if [ $? != 0 ]; then
     echo "ERROR: Unable to Initialize Gerrit"
     exit 1
   fi
 
   su - vcap -c "LD_LIBRARY_PATH=$PACKAGE_DIR/lib:$LD_LIBRARY_PATH PATH=$PACKAGE_DIR/bin/:$GIT_DIR/bin/:$JAVA_DIR/bin:$PATH $DATA_DIR/review_site/$dbname/bin/gerrit.sh stop "
+fi
+
+if [ $NEED_UPGRADE != 0 ] && [ -d $CONFIG_DIR ]; then
+  $JOB_DIR/bin/upgrade_expect $VERSION
+  if [ $? != 0 ]; then
+    echo "ERROR: Unable to Upgrade Gerrit"
+    exit 1
+  fi
 fi
 
 # Harden Secure Configurations
@@ -41,7 +51,15 @@ cp -pf $JOB_DIR/config/secure.config $CONFIG_DIR/
 # Replication setup
 cp -pf $JOB_DIR/config/replication.config $CONFIG_DIR/
 
-# Passwdless ssh key pair refresh/generation (for replication)
-rm -rf /home/vcap/.ssh/*
-$JOB_DIR/bin/ssh_expect
+# Gerrit Hooks setup
+rm -rf $CONFIG_DIR/../hooks
+cp -r $PACKAGE_DIR/hooks $CONFIG_DIR/../
+cp -pf $JOB_DIR/config/gerrit_hooks.yml $CONFIG_DIR/../hooks/patchset_notification/config/
+cp -pf $JOB_DIR/config/review* $CONFIG_DIR/../hooks/patchset_notification/config/
+chown -R vcap:vcap $CONFIG_DIR/../hooks/
 
+# Passwdless ssh key pair refresh/generation (for replication)
+if [ ! -f /home/vcap/.ssh/id_rsa.pub ]; then
+  rm -rf /home/vcap/.ssh/*
+  $JOB_DIR/bin/ssh_expect
+fi
