add erb configuration files, split java to another package, and some cleanups.
Change-Id: Ie2b8f16ec16cd876ba039dc46796a61f6905df17

diff --git a/jobs/gerrit/templates/gerrit_init.ctl.erb b/jobs/gerrit/templates/gerrit_init.ctl.erb
--- a/jobs/gerrit/templates/gerrit_init.ctl.erb
+++ b/jobs/gerrit/templates/gerrit_init.ctl.erb
@@ -1,43 +1,35 @@
 #!/bin/bash
 PACKAGE_DIR=/var/vcap/packages/gerrit
 GIT_DIR=/var/vcap/packages/git
+JAVA_DIR=/var/vcap/packages/java
 JOB_DIR=/var/vcap/jobs/gerrit
 DATA_DIR=/var/vcap/store/gerrit
-CONFIG=$DATA_DIR/review_site/<%= properties.gerrit_postgres.dbname %>/etc/gerrit.config
-CONFIG_REP=$DATA_DIR/review_site/<%= properties.gerrit_postgres.dbname %>/etc/replication.config
+CONFIG_DIR=$DATA_DIR/review_site/<%= properties.gerrit_postgres.dbname %>/etc/
 
 chown vcap:vcap $PACKAGE_DIR/gerrit-2.1-SNAPSHOT.war
 
 # Use dbname as subdir for gerrit to make sure below scripts executed after dbname changed in deployment yaml.
-if [ ! -f $CONFIG ]; then
-	mkdir -p $DATA_DIR/review_site/<%= properties.gerrit_postgres.dbname %>
-	chown vcap:vcap $DATA_DIR/review_site/<%= properties.gerrit_postgres.dbname %>
+if [ ! -d $CONFIG_DIR ]; then
+  mkdir -p $DATA_DIR/review_site/<%= properties.gerrit_postgres.dbname %>
+  chown vcap:vcap $DATA_DIR/review_site/<%= properties.gerrit_postgres.dbname %>
 
-	#use expect to finish general initializations for keyfile generation which seems only avaliable via interaction. 
-	$JOB_DIR/bin/gerrit_expect
+  #use expect to general default initilization.
+  $JOB_DIR/bin/gerrit_expect
 
-	if [ $? != 0 ]; then
-        	echo "ERROR: Unable to Initialize Gerrit"
-        	exit 1
-	fi
+  if [ $? != 0 ]; then
+    echo "ERROR: Unable to Initialize Gerrit"
+    exit 1
+  fi
 
-	su - vcap -c "LD_LIBRARY_PATH=$PACKAGE_DIR/lib:$LD_LIBRARY_PATH PATH=$PACKAGE_DIR/bin/:$GIT_DIR/bin/:$PATH $DATA_DIR/review_site/<%= properties.gerrit_postgres.dbname %>/bin/gerrit.sh stop "
+  su - vcap -c "LD_LIBRARY_PATH=$PACKAGE_DIR/lib:$LD_LIBRARY_PATH PATH=$PACKAGE_DIR/bin/:$GIT_DIR/bin/:$JAVA_DIR/bin:$PATH $DATA_DIR/review_site/<%= properties.gerrit_postgres.dbname %>/bin/gerrit.sh stop "
 fi
 
-# Update the configuration files and urls.
-sed -i "s/\(hostname =\).*/\1 <%= properties.gerrit_postgres.address %>/" $CONFIG
-sed -i "s/\(port =\).*/\1 <%= properties.gerrit_postgres.port %>/" $CONFIG
-
-<% if properties.gerrit && properties.gerrit.uri %>
-sed -i "s/\(canonicalWebUrl = https\?:\/\/\).*/\1<%= properties.gerrit.uri %>/" $CONFIG
-<% else %>
-sed -i "s/\(canonicalWebUrl = https\?:\/\/\).*/\1gerrit.<%= properties.domain %>/" $CONFIG
-<% end %>
-sed -i "s/\(listenAddress =\).*/\1 *:<%= properties.gerrit.ssh_port || 29418 %>/" $CONFIG
-sed -i "s/\(listenUrl =\).*/\1 proxy-http:\/\/127.0.0.1:<%= properties.gerrit.http_port || 8443 %>\//" $CONFIG
+# General Configurations
+cp -rf $JOB_DIR/config/gerrit.config $CONFIG_DIR/
+cp -rf $JOB_DIR/config/secure.config $CONFIG_DIR/
 
 # Replication setup
-cp -rf $JOB_DIR/config/replication.config $CONFIG_REP
+cp -rf $JOB_DIR/config/replication.config $CONFIG_DIR/
 
 # Passwdless ssh key pair refresh/generation (for replication)
 rm -rf /home/vcap/.ssh/*
